# Generated by Django 2.0.5 on 2018-05-17 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dep', models.DateTimeField(verbose_name='departure_date')),
                ('date_arr', models.DateTimeField(verbose_name='arrival_date')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.Airplane')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_from', to='flights.City')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_to', to='flights.City')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(to='flights.Passenger'),
        ),
    ]
