# Generated by Django 2.0.5 on 2018-06-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_first_name', models.CharField(max_length=30)),
                ('c_last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(default=[], to='flights.Passenger'),
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='flights.Crew'),
        ),
    ]
